version: '2'
services:
  web:
    build: .
    volumes:
      - .:/web
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DJANGO_SETTINGS_MODULE=MaxBlog.settings.dev
      - PY_AUTORELOAD=1
      - PYTHONUNBUFFERED=1
      - POSTGRES_PASSWORD=test37
    command: /bin/bash -c "cd /web && pip3 install -r ./requirements.txt && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8080"

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=test37
    command: postgres

