# Generated by Django 2.1.5 on 2019-02-12 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Creating time')),
                ('update_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Last changing time')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('second_title', models.CharField(max_length=200, verbose_name='Second Title')),
                ('text', models.TextField(verbose_name='News text')),
                ('category', models.CharField(max_length=20, verbose_name='Category')),
                ('image', models.ImageField(null=True, upload_to='news_images/', verbose_name='News image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'News',
                'ordering': ('-created_datetime',),
                'verbose_name_plural': 'News',
            },
        ),
    ]
