# Generated by Django 2.0.5 on 2019-08-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Web Design', 'Web Design'), ('JavaScript', 'JavaScript'), ('CSS', 'CSS'), ('CSS', 'CSS')], max_length=100, verbose_name='Category'),
        ),
    ]
