# Generated by Django 2.0.5 on 2019-08-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20190807_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Web Design', 'Web Design'), ('JavaScript', 'JavaScript'), ('CSS', 'CSS'), ('Jquery', 'Jquery')], max_length=100, verbose_name='Category'),
        ),
    ]
