# Generated by Django 2.0.5 on 2019-08-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190212_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/index.png', null=True, upload_to='avatars/', verbose_name='avatar'),
        ),
    ]
